[package]
name = "maze_wasm"
version = "0.1.0"

[dependencies]
wasm-bindgen = "0.2.83"
wee_alloc = "0.4.5"

[lib]
crate-type = ["cdylib"]

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
